In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Dataset_final(anime).csv to Dataset_final(anime).csv

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving rating.csv to rating.csv

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Data_Final/anime.csv')
df.head(10)

,Unnamed: 0,anime_id,name,genre,type,episodes,rating,members
0,0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
5,5,32935,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...,"Comedy, Drama, School, Shounen, Sports",TV,10,9.15,93351
6,6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
7,7,820,Ginga Eiyuu Densetsu,"Drama, Military, Sci-Fi, Space",OVA,110,9.11,80679
8,8,15335,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien...,"Action, Comedy, Historical, Parody, Samurai, S...",Movie,1,9.10,72534
9,9,15417,Gintama&#039;: Enchousen,"Action, Comedy, Historical, Parody, Samurai, S...",TV,13,9.11,81109

In [ ]:
dft = pd.read_csv('/content/drive/MyDrive/Data_Final/rating.csv')
dft.head(10)

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1
5        1       355      -1
6        1       356      -1
7        1       442      -1
8        1       487      -1
9        1       846      -1

In [ ]:
print("Anime:\n")
print(df.info())
print("\n","*"*50,"\nRating:\n")
print(dft.info())

Anime:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12064 entries, 0 to 12063
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  12064 non-null  int64
 1   anime_id    12064 non-null  int64
 2   name        12064 non-null  object
 3   genre       12064 non-null  object
 4   type        12064 non-null  object
 5   episodes    12064 non-null  object
 6   rating      12064 non-null  float64
 7   members     12064 non-null  int64
dtypes: float64(1), int64(3), object(4)
memory usage: 754.1+ KB
None

 **************************************************
Rating:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB
None

In [ ]:
print("Anime missing values (%):\n")
print(round(df.isnull().sum().sort_values(ascending=False)/len(df.index),4)*100)
print("\n","*"*50,"\n\nRating missing values (%):\n")
print(round(dft.isnull().sum().sort_values(ascending=False)/len(dft.index),4)*100)

Anime missing values (%):

Unnamed: 0    0.0
anime_id      0.0
name          0.0
genre         0.0
type          0.0
episodes      0.0
rating        0.0
members       0.0
dtype: float64

 **************************************************

Rating missing values (%):

user_id     0.0
anime_id    0.0
rating      0.0
dtype: float64

In [ ]:
print(df['type'].mode())
print(df['genre'].mode())

0    TV
dtype: object
0    Hentai
dtype: object

In [ ]:
df=df[~np.isnan(df["rating"])]

df['genre'] = df['genre'].fillna(
df['genre'].dropna().mode().values[0])

df['type'] = df['type'].fillna(
df['type'].dropna().mode().values[0])

df.isnull().sum()

Unnamed: 0    0
anime_id      0
name          0
genre         0
type          0
episodes      0
rating        0
members       0
dtype: int64

In [ ]:
df.isnull().sum()

Unnamed: 0    0
anime_id      0
name          0
genre         0
type          0
episodes      0
rating        0
members       0
dtype: int64

In [ ]:
dftt = df.drop(columns=['Unnamed: 0', 'type', 'episodes', 'members'])

In [ ]:
dftt.head()

,anime_id,name,genre,rating
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25
3,9253,Steins;Gate,"Sci-Fi, Thriller",9.17
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16

In [ ]:
dftt["genre"] = dftt["genre"].str.replace(", ", ",")

# Then convert the genre column into a list so you can hot one encode the genres.
dftt["genre"] = dftt["genre"].str.split(",")

dftt.head()

,anime_id,name,genre
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]"
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,"[Sci-Fi, Thriller]"
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ..."

In [ ]:
# Using scikit learn's MLB package to one hot encode the genres
from sklearn.preprocessing import MultiLabelBinarizer

# Code from https://stackoverflow.com/questions/45312377/how-to-one-hot-encode-from-a-pandas-column-containing-a-list
mlb = MultiLabelBinarizer(sparse_output=True)

dftt = dftt.join(pd.DataFrame.sparse.from_spmatrix(
                mlb.fit_transform(dftt["genre"]),
                index=dftt.index,
                columns=mlb.classes_))

# Drop the origininal genre column
dftt.drop("genre", axis=1, inplace=True)

In [ ]:
dftt.head()

,anime_id,name,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,...,Shounen Ai,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri
0,32281,Kimi no Na wa.,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,9969,Gintama&#039;,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
dft.dropna(inplace=True)

In [ ]:
dft.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [ ]:
dft = dft[dft["user_id"]==4271]

# Reset the indexes
dft.reset_index(drop=True, inplace=True)
# Drop the columns that are not needed
dft = dft.drop("user_id", axis=1)

In [ ]:
dft

    anime_id  rating
0       1604       8
1       2251       9
2       6746      10
3       8129      10
4       8740      -1
5       9863      10
6       9969      10
7      11741      -1
8      11771      10
9      11843      10
10     13601      10
11     14513      10
12     16498      10
13     16894      10
14     18115      10
15     18679      10

In [ ]:
user_genre_df = dftt[dftt["anime_id"].isin(dft["anime_id"])]
user_genre_df

,anime_id,name,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,...,Shounen Ai,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri
4,9969,Gintama&#039;,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,11741,Fate/Zero 2nd Season,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
40,1535,Death Note,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
66,777,Hellsing Ultimate,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
72,16894,Kuroko no Basket 2nd Season,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
84,2251,Baccano!,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
86,16498,Shingeki no Kyojin,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
98,13601,Psycho-Pass,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,18115,Magi: The Kingdom of Magic,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122,11771,Kuroko no Basket,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
146,139,Hunter x Hunter: Greed Island Final,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
166,6746,Durarara!!,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
175,1604,Katekyo Hitman Reborn!,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
183,9863,SKET Dance,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
185,11843,Danshi Koukousei no Nichijou,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
202,138,Hunter x Hunter: Greed Island,1,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
267,8129,Kuragehime,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
268,14513,Magi: The Labyrinth of Magic,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281,18679,Kill la Kill,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
352,8740,One Piece Film: Strong World Episode 0,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
dftt.to_csv('/content/drive/MyDrive/Data_Final/anime.csv')

In [ ]:
dftt

,anime_id,name,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,...,Shounen Ai,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri
0,32281,Kimi no Na wa.,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,5114,Fullmetal Alchemist: Brotherhood,1,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,28977,Gintama°,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9253,Steins;Gate,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,9969,Gintama&#039;,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12059,9316,Toushindai My Lover: Minami tai Mecha-Minami,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12060,5543,Under World,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12061,5621,Violence Gekiga David no Hoshi,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12062,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12063,26081,Yasuji no Pornorama: Yacchimae!!,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
dft.to_csv('/content/drive/MyDrive/Data_Final/rating.csv')

In [ ]:
user_genre_df = dftt[dftt["anime_id"].isin(dft["anime_id"])]
user_genre_df

,anime_id,name,Action,Adventure,Cars,Comedy,Dementia,Demons,Drama,Ecchi,...,Shounen Ai,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Vampire,Yaoi,Yuri
4,9969,Gintama&#039;,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
36,11741,Fate/Zero 2nd Season,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
40,1535,Death Note,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
66,777,Hellsing Ultimate,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
72,16894,Kuroko no Basket 2nd Season,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
84,2251,Baccano!,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
86,16498,Shingeki no Kyojin,1,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
98,13601,Psycho-Pass,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,18115,Magi: The Kingdom of Magic,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122,11771,Kuroko no Basket,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
166,6746,Durarara!!,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
175,1604,Katekyo Hitman Reborn!,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
183,9863,SKET Dance,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
185,11843,Danshi Koukousei no Nichijou,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
267,8129,Kuragehime,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
268,14513,Magi: The Labyrinth of Magic,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
281,18679,Kill la Kill,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
352,8740,One Piece Film: Strong World Episode 0,1,1,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
dft.drop([0, 1], axis=0, inplace=True)
dft.reset_index(drop=True, inplace=True)
dft

    anime_id  rating
0       1604       8
1       2251       9
2       6746      10
3       8129      10
4       8740      -1
5       9863      10
6       9969      10
7      11741      -1
8      11771      10
9      11843      10
10     13601      10
11     14513      10
12     16498      10
13     16894      10
14     18115      10
15     18679      10